2018-10-20 20:27:33.216 [error] <0.494.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.499.0> exit with reason normal in context child_terminated
2018-10-20 20:27:34.519 [error] emulator Error in process <0.613.0> with exit value:
{{nocatch,{1,3,4}},[{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,8}]}]}
2018-10-20 20:27:35.528 [error] emulator Error in process <0.629.0> with exit value:
{{nocatch,{1,3,4}},[{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,8}]}]}
2018-10-20 20:27:36.533 [error] emulator Error in process <0.645.0> with exit value:
{{nocatch,{1,3,4}},[{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,8}]}]}
2018-10-20 20:27:37.541 [error] emulator Error in process <0.661.0> with exit value:
{{nocatch,{1,3,4}},[{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,8}]}]}
2018-10-20 20:32:04.027 [error] <0.148.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.153.0> exit with reason normal in context child_terminated
2018-10-20 20:32:04.659 [error] <0.203.0> Supervisor 'Elixir.Tackle.Supervisor' had child 'Elixir.Tackle.Connection' started with 'Elixir.Tackle.Connection':start_link() at <0.204.0> exit with reason killed in context child_terminated
2018-10-20 20:32:05.955 [error] emulator Error in process <0.649.0> with exit value:
{badarith,[{'Elixir.Tackle.RepublishTest.BrokenConsumer',handle_message,1,[{file,"test/integration/republish_test.exs"},{line,17}]},{'Elixir.Tackle.RepublishTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/republish_test.exs"},{line,8}]}]}
2018-10-20 20:32:05.967 [error] emulator Error in process <0.677.0> with exit value:
{badarith,[{'Elixir.Tackle.RepublishTest.BrokenConsumer',handle_message,1,[{file,"test/integration/republish_test.exs"},{line,17}]},{'Elixir.Tackle.RepublishTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/republish_test.exs"},{line,8}]}]}
2018-10-20 20:32:06.002 [error] emulator Error in process <0.756.0> with exit value:
{badarith,[{'Elixir.Tackle.RepublishTest.BrokenConsumer',handle_message,1,[{file,"test/integration/republish_test.exs"},{line,17}]},{'Elixir.Tackle.RepublishTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/republish_test.exs"},{line,8}]}]}
2018-10-20 20:32:06.014 [error] emulator Error in process <0.771.0> with exit value:
{badarith,[{'Elixir.Tackle.RepublishTest.BrokenConsumer',handle_message,1,[{file,"test/integration/republish_test.exs"},{line,17}]},{'Elixir.Tackle.RepublishTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/republish_test.exs"},{line,8}]}]}
2018-10-20 20:32:06.026 [error] emulator Error in process <0.786.0> with exit value:
{badarith,[{'Elixir.Tackle.RepublishTest.BrokenConsumer',handle_message,1,[{file,"test/integration/republish_test.exs"},{line,17}]},{'Elixir.Tackle.RepublishTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/republish_test.exs"},{line,8}]}]}
2018-10-20 20:32:06.035 [error] emulator Error in process <0.801.0> with exit value:
{badarith,[{'Elixir.Tackle.RepublishTest.BrokenConsumer',handle_message,1,[{file,"test/integration/republish_test.exs"},{line,17}]},{'Elixir.Tackle.RepublishTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/republish_test.exs"},{line,8}]}]}
2018-10-20 20:32:07.190 [error] emulator Error in process <0.887.0> with exit value:
{badarith,[{'Elixir.Tackle.RepublishTest.BrokenConsumer',handle_message,1,[{file,"test/integration/republish_test.exs"},{line,17}]},{'Elixir.Tackle.RepublishTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/republish_test.exs"},{line,8}]}]}
2018-10-20 20:32:07.412 [error] emulator Error in process <0.902.0> with exit value:
{badarith,[{'Elixir.Tackle.RepublishTest.BrokenConsumer',handle_message,1,[{file,"test/integration/republish_test.exs"},{line,17}]},{'Elixir.Tackle.RepublishTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/republish_test.exs"},{line,8}]}]}
2018-10-20 20:32:12.493 [error] emulator Error in process <0.1000.0> with exit value:
{badarith,[{'Elixir.Tackle.RepublishTest.BrokenConsumer',handle_message,1,[{file,"test/integration/republish_test.exs"},{line,17}]},{'Elixir.Tackle.RepublishTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/republish_test.exs"},{line,8}]}]}
2018-10-20 20:32:12.702 [error] emulator Error in process <0.1028.0> with exit value:
{badarith,[{'Elixir.Tackle.RepublishTest.BrokenConsumer',handle_message,1,[{file,"test/integration/republish_test.exs"},{line,17}]},{'Elixir.Tackle.RepublishTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/republish_test.exs"},{line,8}]}]}
2018-10-20 20:32:12.912 [error] emulator Error in process <0.1056.0> with exit value:
{badarith,[{'Elixir.Tackle.RepublishTest.BrokenConsumer',handle_message,1,[{file,"test/integration/republish_test.exs"},{line,17}]},{'Elixir.Tackle.RepublishTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/republish_test.exs"},{line,8}]}]}
2018-10-20 20:32:13.508 [error] emulator Error in process <0.1071.0> with exit value:
{badarith,[{'Elixir.Tackle.RepublishTest.BrokenConsumer',handle_message,1,[{file,"test/integration/republish_test.exs"},{line,17}]},{'Elixir.Tackle.RepublishTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/republish_test.exs"},{line,8}]}]}
2018-10-20 20:32:13.709 [error] emulator Error in process <0.1086.0> with exit value:
{badarith,[{'Elixir.Tackle.RepublishTest.BrokenConsumer',handle_message,1,[{file,"test/integration/republish_test.exs"},{line,17}]},{'Elixir.Tackle.RepublishTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/republish_test.exs"},{line,8}]}]}
2018-10-20 20:32:13.925 [error] emulator Error in process <0.1101.0> with exit value:
{badarith,[{'Elixir.Tackle.RepublishTest.BrokenConsumer',handle_message,1,[{file,"test/integration/republish_test.exs"},{line,17}]},{'Elixir.Tackle.RepublishTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/republish_test.exs"},{line,8}]}]}
2018-10-20 20:32:25.914 [error] <0.1249.0>@rabbit_binary_generator:build_content_frames:95 CRASH REPORT Process <0.1249.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(125) in rabbit_binary_generator:build_content_frames/7 line 95
2018-10-20 20:32:25.915 [error] <0.1246.0>@rabbit_binary_generator:build_content_frames:95 Supervisor {<0.1246.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.8878>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.1248.0>, {<<"client 127.0.0.1:41486 -> 127.0.0.1:5672">>,1}) at <0.1249.0> exit with reason bad argument in call to erlang:size(125) in rabbit_binary_generator:build_content_frames/7 line 95 in context child_terminated
2018-10-20 20:32:25.915 [error] <0.1246.0> Supervisor {<0.1246.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.8878>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.1248.0>, {<<"client 127.0.0.1:41486 -> 127.0.0.1:5672">>,1}) at <0.1249.0> exit with reason reached_max_restart_intensity in context shutdown
2018-10-20 20:32:25.916 [error] <0.203.0> Supervisor 'Elixir.Tackle.Supervisor' had child 'Elixir.Tackle.Connection' started with 'Elixir.Tackle.Connection':start_link() at <0.339.0> exit with reason killed in context child_terminated
2018-10-20 20:32:25.917 [error] emulator Error in process <0.1253.0> with exit value:
{badarith,[{'Elixir.Tackle.DeliveryHandlerTest','-test delivery consume generates arithmetic exception/1-fun-1-',0,[{file,"test/lib/tackle/delivery_handler_test.exs"},{line,27}]}]}
2018-10-20 20:32:25.917 [error] emulator Error in process <0.1257.0> with exit value:
{{nocatch,{error,12}},[{'Elixir.Tackle.DeliveryHandlerTest','-test delivery consume throws/1-fun-1-',0,[{file,"test/lib/tackle/delivery_handler_test.exs"},{line,39}]}]}
2018-10-20 20:32:25.917 [error] emulator Error in process <0.1259.0> with exit value:
{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"foo">>},[{'Elixir.Tackle.DeliveryHandlerTest','-test delivery consume raises/1-fun-1-',0,[{file,"test/lib/tackle/delivery_handler_test.exs"},{line,33}]}]}
2018-10-20 20:32:26.024 [error] <0.1266.0> Supervisor {<0.1266.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1267.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.1268.0> exit with reason killed in context child_terminated
2018-10-20 20:32:26.025 [error] <0.1266.0> Supervisor {<0.1266.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1267.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.1268.0> exit with reason reached_max_restart_intensity in context shutdown
2018-10-20 20:32:26.065 [error] emulator Error in process <0.1332.0> with exit value:
{badarith,[{'Elixir.Tackle.DeadQueueTest.DeadConsumer',handle_message,1,[{file,"test/integration/dead_queue_test.exs"},{line,16}]},{'Elixir.Tackle.DeadQueueTest.DeadConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/dead_queue_test.exs"},{line,7}]}]}
2018-10-20 20:32:26.073 [error] emulator Error in process <0.1347.0> with exit value:
{badarith,[{'Elixir.Tackle.DeadQueueTest.DeadConsumer',handle_message,1,[{file,"test/integration/dead_queue_test.exs"},{line,16}]},{'Elixir.Tackle.DeadQueueTest.DeadConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/dead_queue_test.exs"},{line,7}]}]}
2018-10-20 20:32:26.083 [error] emulator Error in process <0.1362.0> with exit value:
{badarith,[{'Elixir.Tackle.DeadQueueTest.DeadConsumer',handle_message,1,[{file,"test/integration/dead_queue_test.exs"},{line,16}]},{'Elixir.Tackle.DeadQueueTest.DeadConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/dead_queue_test.exs"},{line,7}]}]}
2018-10-20 20:32:26.090 [error] emulator Error in process <0.1377.0> with exit value:
{badarith,[{'Elixir.Tackle.DeadQueueTest.DeadConsumer',handle_message,1,[{file,"test/integration/dead_queue_test.exs"},{line,16}]},{'Elixir.Tackle.DeadQueueTest.DeadConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/dead_queue_test.exs"},{line,7}]}]}
2018-10-20 20:32:27.073 [error] emulator Error in process <0.1592.0> with exit value:
{badarith,[{'Elixir.Tackle.DeadQueueTest.DeadConsumer',handle_message,1,[{file,"test/integration/dead_queue_test.exs"},{line,16}]},{'Elixir.Tackle.DeadQueueTest.DeadConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/dead_queue_test.exs"},{line,7}]}]}
2018-10-20 20:32:27.084 [error] emulator Error in process <0.1626.0> with exit value:
{badarith,[{'Elixir.Tackle.DeadQueueTest.DeadConsumer',handle_message,1,[{file,"test/integration/dead_queue_test.exs"},{line,16}]},{'Elixir.Tackle.DeadQueueTest.DeadConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/dead_queue_test.exs"},{line,7}]}]}
2018-10-20 20:32:28.082 [error] emulator Error in process <0.1866.0> with exit value:
{badarith,[{'Elixir.Tackle.DeadQueueTest.DeadConsumer',handle_message,1,[{file,"test/integration/dead_queue_test.exs"},{line,16}]},{'Elixir.Tackle.DeadQueueTest.DeadConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/dead_queue_test.exs"},{line,7}]}]}
2018-10-20 20:32:28.098 [error] emulator Error in process <0.1881.0> with exit value:
{badarith,[{'Elixir.Tackle.DeadQueueTest.DeadConsumer',handle_message,1,[{file,"test/integration/dead_queue_test.exs"},{line,16}]},{'Elixir.Tackle.DeadQueueTest.DeadConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/dead_queue_test.exs"},{line,7}]}]}
2018-10-20 20:32:28.121 [error] emulator Error in process <0.1896.0> with exit value:
{badarith,[{'Elixir.Tackle.DeadQueueTest.DeadConsumer',handle_message,1,[{file,"test/integration/dead_queue_test.exs"},{line,16}]},{'Elixir.Tackle.DeadQueueTest.DeadConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/dead_queue_test.exs"},{line,7}]}]}
2018-10-20 20:32:28.127 [error] emulator Error in process <0.1911.0> with exit value:
{badarith,[{'Elixir.Tackle.DeadQueueTest.DeadConsumer',handle_message,1,[{file,"test/integration/dead_queue_test.exs"},{line,16}]},{'Elixir.Tackle.DeadQueueTest.DeadConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/dead_queue_test.exs"},{line,7}]}]}
2018-10-20 20:32:28.138 [error] emulator Error in process <0.1926.0> with exit value:
{badarith,[{'Elixir.Tackle.DeadQueueTest.DeadConsumer',handle_message,1,[{file,"test/integration/dead_queue_test.exs"},{line,16}]},{'Elixir.Tackle.DeadQueueTest.DeadConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/dead_queue_test.exs"},{line,7}]}]}
2018-10-20 20:32:29.089 [error] emulator Error in process <0.2121.0> with exit value:
{badarith,[{'Elixir.Tackle.DeadQueueTest.DeadConsumer',handle_message,1,[{file,"test/integration/dead_queue_test.exs"},{line,16}]},{'Elixir.Tackle.DeadQueueTest.DeadConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/dead_queue_test.exs"},{line,7}]}]}
2018-10-20 20:32:29.126 [error] emulator Error in process <0.2136.0> with exit value:
{badarith,[{'Elixir.Tackle.DeadQueueTest.DeadConsumer',handle_message,1,[{file,"test/integration/dead_queue_test.exs"},{line,16}]},{'Elixir.Tackle.DeadQueueTest.DeadConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/dead_queue_test.exs"},{line,7}]}]}
2018-10-20 20:32:29.135 [error] emulator Error in process <0.2151.0> with exit value:
{badarith,[{'Elixir.Tackle.DeadQueueTest.DeadConsumer',handle_message,1,[{file,"test/integration/dead_queue_test.exs"},{line,16}]},{'Elixir.Tackle.DeadQueueTest.DeadConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/dead_queue_test.exs"},{line,7}]}]}
2018-10-20 20:32:29.138 [error] emulator Error in process <0.2166.0> with exit value:
{badarith,[{'Elixir.Tackle.DeadQueueTest.DeadConsumer',handle_message,1,[{file,"test/integration/dead_queue_test.exs"},{line,16}]},{'Elixir.Tackle.DeadQueueTest.DeadConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/dead_queue_test.exs"},{line,7}]}]}
2018-10-20 20:32:29.145 [error] emulator Error in process <0.2181.0> with exit value:
{badarith,[{'Elixir.Tackle.DeadQueueTest.DeadConsumer',handle_message,1,[{file,"test/integration/dead_queue_test.exs"},{line,16}]},{'Elixir.Tackle.DeadQueueTest.DeadConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/dead_queue_test.exs"},{line,7}]}]}
2018-10-20 20:32:30.140 [error] emulator Error in process <0.2376.0> with exit value:
{badarith,[{'Elixir.Tackle.DeadQueueTest.DeadConsumer',handle_message,1,[{file,"test/integration/dead_queue_test.exs"},{line,16}]},{'Elixir.Tackle.DeadQueueTest.DeadConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/dead_queue_test.exs"},{line,7}]}]}
2018-10-20 20:32:42.237 [error] emulator Error in process <0.2591.0> with exit value:
{badarith,[{'Elixir.Tackle.BrokenConsumerTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_test.exs"},{line,8}]}]}
2018-10-20 20:32:42.243 [error] emulator Error in process <0.2607.0> with exit value:
{badarith,[{'Elixir.Tackle.BrokenConsumerTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_test.exs"},{line,8}]}]}
2018-10-20 20:32:42.255 [error] emulator Error in process <0.2623.0> with exit value:
{badarith,[{'Elixir.Tackle.BrokenConsumerTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_test.exs"},{line,8}]}]}
2018-10-20 20:32:42.263 [error] emulator Error in process <0.2639.0> with exit value:
{badarith,[{'Elixir.Tackle.BrokenConsumerTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_test.exs"},{line,8}]}]}
2018-10-20 20:32:42.270 [error] emulator Error in process <0.2655.0> with exit value:
{badarith,[{'Elixir.Tackle.BrokenConsumerTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_test.exs"},{line,8}]}]}
2018-10-20 20:32:43.242 [error] emulator Error in process <0.2818.0> with exit value:
{badarith,[{'Elixir.Tackle.BrokenConsumerTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_test.exs"},{line,8}]}]}
2018-10-20 20:32:43.254 [error] emulator Error in process <0.2844.0> with exit value:
{badarith,[{'Elixir.Tackle.BrokenConsumerTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_test.exs"},{line,8}]}]}
2018-10-20 20:32:43.261 [error] emulator Error in process <0.2860.0> with exit value:
{badarith,[{'Elixir.Tackle.BrokenConsumerTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_test.exs"},{line,8}]}]}
2018-10-20 20:32:43.269 [error] emulator Error in process <0.2876.0> with exit value:
{badarith,[{'Elixir.Tackle.BrokenConsumerTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_test.exs"},{line,8}]}]}
2018-10-20 20:32:44.249 [error] emulator Error in process <0.3068.0> with exit value:
{badarith,[{'Elixir.Tackle.BrokenConsumerTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_test.exs"},{line,8}]}]}
2018-10-20 20:32:44.261 [error] emulator Error in process <0.3084.0> with exit value:
{badarith,[{'Elixir.Tackle.BrokenConsumerTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_test.exs"},{line,8}]}]}
2018-10-20 20:32:44.270 [error] emulator Error in process <0.3100.0> with exit value:
{badarith,[{'Elixir.Tackle.BrokenConsumerTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_test.exs"},{line,8}]}]}
2018-10-20 20:32:44.290 [error] emulator Error in process <0.3116.0> with exit value:
{badarith,[{'Elixir.Tackle.BrokenConsumerTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_test.exs"},{line,8}]}]}
2018-10-20 20:32:44.302 [error] emulator Error in process <0.3132.0> with exit value:
{badarith,[{'Elixir.Tackle.BrokenConsumerTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_test.exs"},{line,8}]}]}
2018-10-20 20:32:45.260 [error] emulator Error in process <0.3308.0> with exit value:
{badarith,[{'Elixir.Tackle.BrokenConsumerTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_test.exs"},{line,8}]}]}
2018-10-20 20:32:45.276 [error] emulator Error in process <0.3324.0> with exit value:
{badarith,[{'Elixir.Tackle.BrokenConsumerTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_test.exs"},{line,8}]}]}
2018-10-20 20:32:45.290 [error] emulator Error in process <0.3340.0> with exit value:
{badarith,[{'Elixir.Tackle.BrokenConsumerTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_test.exs"},{line,8}]}]}
2018-10-20 20:32:45.303 [error] emulator Error in process <0.3356.0> with exit value:
{badarith,[{'Elixir.Tackle.BrokenConsumerTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_test.exs"},{line,8}]}]}
2018-10-20 20:32:45.310 [error] emulator Error in process <0.3372.0> with exit value:
{badarith,[{'Elixir.Tackle.BrokenConsumerTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_test.exs"},{line,8}]}]}
2018-10-20 20:32:46.287 [error] emulator Error in process <0.3548.0> with exit value:
{badarith,[{'Elixir.Tackle.BrokenConsumerTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_test.exs"},{line,8}]}]}
2018-10-20 20:32:54.298 [error] emulator Error in process <0.4703.0> with exit value:
{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Raised!">>},[{'Elixir.Tackle.BrokenConsumerRaisesTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_raises_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerRaisesTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_raises_test.exs"},{line,8}]}]}
2018-10-20 20:32:54.306 [error] emulator Error in process <0.4719.0> with exit value:
{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Raised!">>},[{'Elixir.Tackle.BrokenConsumerRaisesTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_raises_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerRaisesTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_raises_test.exs"},{line,8}]}]}
2018-10-20 20:32:54.316 [error] emulator Error in process <0.4735.0> with exit value:
{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Raised!">>},[{'Elixir.Tackle.BrokenConsumerRaisesTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_raises_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerRaisesTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_raises_test.exs"},{line,8}]}]}
2018-10-20 20:32:54.325 [error] emulator Error in process <0.4751.0> with exit value:
{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Raised!">>},[{'Elixir.Tackle.BrokenConsumerRaisesTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_raises_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerRaisesTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_raises_test.exs"},{line,8}]}]}
2018-10-20 20:32:54.332 [error] emulator Error in process <0.4767.0> with exit value:
{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Raised!">>},[{'Elixir.Tackle.BrokenConsumerRaisesTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_raises_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerRaisesTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_raises_test.exs"},{line,8}]}]}
2018-10-20 20:32:54.341 [error] emulator Error in process <0.4783.0> with exit value:
{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Raised!">>},[{'Elixir.Tackle.BrokenConsumerRaisesTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_raises_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerRaisesTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_raises_test.exs"},{line,8}]}]}
2018-10-20 20:32:54.347 [error] emulator Error in process <0.4799.0> with exit value:
{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Raised!">>},[{'Elixir.Tackle.BrokenConsumerRaisesTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_raises_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerRaisesTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_raises_test.exs"},{line,8}]}]}
2018-10-20 20:32:55.308 [error] emulator Error in process <0.5004.0> with exit value:
{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Raised!">>},[{'Elixir.Tackle.BrokenConsumerRaisesTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_raises_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerRaisesTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_raises_test.exs"},{line,8}]}]}
2018-10-20 20:32:55.316 [error] emulator Error in process <0.5020.0> with exit value:
{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Raised!">>},[{'Elixir.Tackle.BrokenConsumerRaisesTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_raises_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerRaisesTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_raises_test.exs"},{line,8}]}]}
2018-10-20 20:32:55.326 [error] emulator Error in process <0.5036.0> with exit value:
{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Raised!">>},[{'Elixir.Tackle.BrokenConsumerRaisesTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_raises_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerRaisesTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_raises_test.exs"},{line,8}]}]}
2018-10-20 20:32:55.335 [error] emulator Error in process <0.5052.0> with exit value:
{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Raised!">>},[{'Elixir.Tackle.BrokenConsumerRaisesTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_raises_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerRaisesTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_raises_test.exs"},{line,8}]}]}
2018-10-20 20:32:56.317 [error] emulator Error in process <0.5308.0> with exit value:
{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Raised!">>},[{'Elixir.Tackle.BrokenConsumerRaisesTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_raises_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerRaisesTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_raises_test.exs"},{line,8}]}]}
2018-10-20 20:32:56.326 [error] emulator Error in process <0.5324.0> with exit value:
{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Raised!">>},[{'Elixir.Tackle.BrokenConsumerRaisesTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_raises_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerRaisesTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_raises_test.exs"},{line,8}]}]}
2018-10-20 20:32:56.340 [error] emulator Error in process <0.5340.0> with exit value:
{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Raised!">>},[{'Elixir.Tackle.BrokenConsumerRaisesTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_raises_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerRaisesTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_raises_test.exs"},{line,8}]}]}
2018-10-20 20:32:56.351 [error] emulator Error in process <0.5356.0> with exit value:
{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Raised!">>},[{'Elixir.Tackle.BrokenConsumerRaisesTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_raises_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerRaisesTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_raises_test.exs"},{line,8}]}]}
2018-10-20 20:32:56.360 [error] emulator Error in process <0.5372.0> with exit value:
{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Raised!">>},[{'Elixir.Tackle.BrokenConsumerRaisesTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_raises_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerRaisesTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_raises_test.exs"},{line,8}]}]}
2018-10-20 20:32:57.328 [error] emulator Error in process <0.5612.0> with exit value:
{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Raised!">>},[{'Elixir.Tackle.BrokenConsumerRaisesTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_raises_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerRaisesTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_raises_test.exs"},{line,8}]}]}
2018-10-20 20:32:57.345 [error] emulator Error in process <0.5628.0> with exit value:
{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Raised!">>},[{'Elixir.Tackle.BrokenConsumerRaisesTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_raises_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerRaisesTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_raises_test.exs"},{line,8}]}]}
2018-10-20 20:32:57.352 [error] emulator Error in process <0.5644.0> with exit value:
{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Raised!">>},[{'Elixir.Tackle.BrokenConsumerRaisesTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_raises_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerRaisesTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_raises_test.exs"},{line,8}]}]}
2018-10-20 20:32:57.360 [error] emulator Error in process <0.5660.0> with exit value:
{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Raised!">>},[{'Elixir.Tackle.BrokenConsumerRaisesTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_raises_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerRaisesTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_raises_test.exs"},{line,8}]}]}
2018-10-20 20:32:57.372 [error] emulator Error in process <0.5676.0> with exit value:
{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Raised!">>},[{'Elixir.Tackle.BrokenConsumerRaisesTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_raises_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerRaisesTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_raises_test.exs"},{line,8}]}]}
2018-10-20 20:32:58.371 [error] emulator Error in process <0.5916.0> with exit value:
{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Raised!">>},[{'Elixir.Tackle.BrokenConsumerRaisesTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_raises_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerRaisesTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_raises_test.exs"},{line,8}]}]}
2018-10-20 20:33:00.318 [error] emulator Error in process <0.5951.0> with exit value:
{{nocatch,{1,3,4}},[{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,8}]}]}
2018-10-20 20:33:00.326 [error] emulator Error in process <0.5967.0> with exit value:
{{nocatch,{1,3,4}},[{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,8}]}]}
2018-10-20 20:33:00.332 [error] emulator Error in process <0.5983.0> with exit value:
{{nocatch,{1,3,4}},[{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,8}]}]}
2018-10-20 20:33:00.346 [error] emulator Error in process <0.5999.0> with exit value:
{{nocatch,{1,3,4}},[{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,8}]}]}
2018-10-20 20:33:00.352 [error] emulator Error in process <0.6015.0> with exit value:
{{nocatch,{1,3,4}},[{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,8}]}]}
2018-10-20 20:33:00.365 [error] emulator Error in process <0.6031.0> with exit value:
{{nocatch,{1,3,4}},[{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,8}]}]}
2018-10-20 20:33:00.372 [error] emulator Error in process <0.6047.0> with exit value:
{{nocatch,{1,3,4}},[{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,8}]}]}
2018-10-20 20:33:01.351 [error] emulator Error in process <0.6146.0> with exit value:
{{nocatch,{1,3,4}},[{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,8}]}]}
2018-10-20 20:33:01.363 [error] emulator Error in process <0.6172.0> with exit value:
{{nocatch,{1,3,4}},[{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,8}]}]}
2018-10-20 20:33:01.372 [error] emulator Error in process <0.6188.0> with exit value:
{{nocatch,{1,3,4}},[{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,8}]}]}
2018-10-20 20:33:01.381 [error] emulator Error in process <0.6204.0> with exit value:
{{nocatch,{1,3,4}},[{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,8}]}]}
2018-10-20 20:33:02.366 [error] emulator Error in process <0.6364.0> with exit value:
{{nocatch,{1,3,4}},[{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,8}]}]}
2018-10-20 20:33:02.382 [error] emulator Error in process <0.6380.0> with exit value:
{{nocatch,{1,3,4}},[{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,8}]}]}
2018-10-20 20:33:02.396 [error] emulator Error in process <0.6396.0> with exit value:
{{nocatch,{1,3,4}},[{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,8}]}]}
2018-10-20 20:33:02.404 [error] emulator Error in process <0.6412.0> with exit value:
{{nocatch,{1,3,4}},[{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,8}]}]}
2018-10-20 20:33:02.415 [error] emulator Error in process <0.6428.0> with exit value:
{{nocatch,{1,3,4}},[{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,8}]}]}
2018-10-20 20:33:03.386 [error] emulator Error in process <0.6572.0> with exit value:
{{nocatch,{1,3,4}},[{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,8}]}]}
2018-10-20 20:33:03.394 [error] emulator Error in process <0.6588.0> with exit value:
{{nocatch,{1,3,4}},[{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,8}]}]}
2018-10-20 20:33:03.404 [error] emulator Error in process <0.6604.0> with exit value:
{{nocatch,{1,3,4}},[{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,8}]}]}
2018-10-20 20:33:03.415 [error] emulator Error in process <0.6620.0> with exit value:
{{nocatch,{1,3,4}},[{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,8}]}]}
2018-10-20 20:33:04.478 [error] emulator Error in process <0.6780.0> with exit value:
{{nocatch,{1,3,4}},[{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,8}]}]}
2018-10-20 20:33:27.697 [error] <0.148.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.153.0> exit with reason normal in context child_terminated
2018-10-20 20:33:27.938 [error] <0.247.0>@rabbit_binary_generator:build_content_frames:95 CRASH REPORT Process <0.247.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(125) in rabbit_binary_generator:build_content_frames/7 line 95
2018-10-20 20:33:27.938 [error] <0.244.0>@rabbit_binary_generator:build_content_frames:95 Supervisor {<0.244.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6208>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.246.0>, {<<"client 127.0.0.1:35351 -> 127.0.0.1:5672">>,1}) at <0.247.0> exit with reason bad argument in call to erlang:size(125) in rabbit_binary_generator:build_content_frames/7 line 95 in context child_terminated
2018-10-20 20:33:27.939 [error] <0.244.0> Supervisor {<0.244.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6208>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.246.0>, {<<"client 127.0.0.1:35351 -> 127.0.0.1:5672">>,1}) at <0.247.0> exit with reason reached_max_restart_intensity in context shutdown
2018-10-20 20:33:30.849 [error] <0.148.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.153.0> exit with reason normal in context child_terminated
2018-10-20 20:33:31.094 [error] <0.247.0>@rabbit_binary_generator:build_content_frames:95 CRASH REPORT Process <0.247.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(125) in rabbit_binary_generator:build_content_frames/7 line 95
2018-10-20 20:33:31.094 [error] <0.244.0>@rabbit_binary_generator:build_content_frames:95 Supervisor {<0.244.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6208>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.246.0>, {<<"client 127.0.0.1:55687 -> 127.0.0.1:5672">>,1}) at <0.247.0> exit with reason bad argument in call to erlang:size(125) in rabbit_binary_generator:build_content_frames/7 line 95 in context child_terminated
2018-10-20 20:33:31.094 [error] <0.244.0> Supervisor {<0.244.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6208>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.246.0>, {<<"client 127.0.0.1:55687 -> 127.0.0.1:5672">>,1}) at <0.247.0> exit with reason reached_max_restart_intensity in context shutdown
2018-10-20 20:33:47.548 [error] <0.148.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.153.0> exit with reason normal in context child_terminated
2018-10-20 20:33:47.754 [error] <0.247.0>@rabbit_binary_generator:build_content_frames:95 CRASH REPORT Process <0.247.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(125) in rabbit_binary_generator:build_content_frames/7 line 95
2018-10-20 20:33:47.755 [error] <0.244.0>@rabbit_binary_generator:build_content_frames:95 Supervisor {<0.244.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6208>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.246.0>, {<<"client 127.0.0.1:36870 -> 127.0.0.1:5672">>,1}) at <0.247.0> exit with reason bad argument in call to erlang:size(125) in rabbit_binary_generator:build_content_frames/7 line 95 in context child_terminated
2018-10-20 20:33:47.755 [error] <0.244.0> Supervisor {<0.244.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6208>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.246.0>, {<<"client 127.0.0.1:36870 -> 127.0.0.1:5672">>,1}) at <0.247.0> exit with reason reached_max_restart_intensity in context shutdown
2020-01-09 10:41:15.051 [error] <0.463.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.468.0> exit with reason normal in context child_terminated
2020-01-09 10:41:20.412 [error] <0.719.0> Supervisor {<0.719.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.720.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,60000,none,[#Fun<amqp_..>,...],...}) at <0.721.0> exit with reason killed in context child_terminated
2020-01-09 10:41:20.446 [error] <0.718.0> gen_server 'Elixir.Tackle.ConnectionErrorsTest.DeadFailConsumer' terminated with reason: {connection_lost,killed}
2020-01-09 10:41:20.446 [error] <0.719.0> Supervisor {<0.719.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.720.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,60000,none,[#Fun<amqp_..>,...],...}) at <0.721.0> exit with reason reached_max_restart_intensity in context shutdown
2020-01-09 10:41:20.446 [error] <0.718.0> CRASH REPORT Process 'Elixir.Tackle.ConnectionErrorsTest.DeadFailConsumer' with 0 neighbours exited with reason: {connection_lost,killed} in gen_server:handle_common_reply/8 line 726
2020-01-09 10:41:20.447 [error] <0.730.0> gen_server <0.730.0> terminated with reason: {infrastructure_died,{writer,send_failed,badarg}}
2020-01-09 10:41:20.447 [error] <0.730.0> CRASH REPORT Process <0.730.0> with 0 neighbours exited with reason: {infrastructure_died,{writer,send_failed,badarg}} in gen_server:handle_common_reply/8 line 726
2020-01-09 10:41:20.447 [error] <0.728.0> Supervisor {<0.728.0>,amqp_channel_sup} had child channel started with amqp_channel:start_link(network, <0.721.0>, 1, <0.729.0>, {<<"client 127.0.0.1:48705 -> 127.0.0.1:5672">>,1}) at <0.730.0> exit with reason {infrastructure_died,{writer,send_failed,badarg}} in context child_terminated
2020-01-09 10:41:20.447 [error] <0.728.0> Supervisor {<0.728.0>,amqp_channel_sup} had child channel started with amqp_channel:start_link(network, <0.721.0>, 1, <0.729.0>, {<<"client 127.0.0.1:48705 -> 127.0.0.1:5672">>,1}) at <0.730.0> exit with reason reached_max_restart_intensity in context shutdown
2020-01-09 10:41:20.447 [error] <0.722.0> Supervisor {<0.722.0>,amqp_channel_sup_sup} had child channel_sup started with amqp_channel_sup:start_link(network, <0.721.0>, <<"client 127.0.0.1:48705 -> 127.0.0.1:5672">>) at undefined exit with reason shutdown in context shutdown_error
2020-01-09 10:41:21.419 [error] emulator Error in process <0.734.0> with exit value:
{badarith,[{'Elixir.Tackle.ConnectionErrorsTest.DeadFailConsumer',handle_message,1,[{file,"test/integration/connection_errors_test.exs"},{line,76}]},{'Elixir.Tackle.ConnectionErrorsTest.DeadFailConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/connection_errors_test.exs"},{line,57}]}]}
2020-01-09 10:41:22.474 [error] <0.764.0> gen_server 'Elixir.Tackle.ConnectionErrorsTest.AckFailConsumer' terminated with reason: {connection_lost,killed}
2020-01-09 10:41:22.475 [error] <0.765.0> Supervisor {<0.765.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.766.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,60000,none,[#Fun<amqp_..>,...],...}) at <0.767.0> exit with reason killed in context child_terminated
2020-01-09 10:41:22.476 [error] <0.765.0> Supervisor {<0.765.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.766.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,60000,none,[#Fun<amqp_..>,...],...}) at <0.767.0> exit with reason reached_max_restart_intensity in context shutdown
2020-01-09 10:41:22.476 [error] <0.764.0> CRASH REPORT Process 'Elixir.Tackle.ConnectionErrorsTest.AckFailConsumer' with 0 neighbours exited with reason: {connection_lost,killed} in gen_server:handle_common_reply/8 line 726
2020-01-09 10:41:22.477 [error] <0.776.0> gen_server <0.776.0> terminated with reason: {infrastructure_died,{writer,send_failed,badarg}}
2020-01-09 10:41:22.477 [error] <0.776.0> CRASH REPORT Process <0.776.0> with 0 neighbours exited with reason: {infrastructure_died,{writer,send_failed,badarg}} in gen_server:handle_common_reply/8 line 726
2020-01-09 10:41:22.478 [error] <0.774.0> Supervisor {<0.774.0>,amqp_channel_sup} had child channel started with amqp_channel:start_link(network, <0.767.0>, 1, <0.775.0>, {<<"client 127.0.0.1:51287 -> 127.0.0.1:5672">>,1}) at <0.776.0> exit with reason {infrastructure_died,{writer,send_failed,badarg}} in context shutdown_error
2020-01-09 10:41:24.512 [error] <0.811.0> Supervisor {<0.811.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.812.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,60000,none,[#Fun<amqp_..>,...],...}) at <0.813.0> exit with reason killed in context child_terminated
2020-01-09 10:41:24.512 [error] <0.810.0> gen_server 'Elixir.Tackle.ConnectionErrorsTest.DelayFailConsumer' terminated with reason: {connection_lost,killed}
2020-01-09 10:41:24.513 [error] <0.811.0> Supervisor {<0.811.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.812.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,60000,none,[#Fun<amqp_..>,...],...}) at <0.813.0> exit with reason reached_max_restart_intensity in context shutdown
2020-01-09 10:41:24.514 [error] <0.810.0> CRASH REPORT Process 'Elixir.Tackle.ConnectionErrorsTest.DelayFailConsumer' with 0 neighbours exited with reason: {connection_lost,killed} in gen_server:handle_common_reply/8 line 726
2020-01-09 10:41:24.515 [error] <0.822.0> gen_server <0.822.0> terminated with reason: {infrastructure_died,{writer,send_failed,badarg}}
2020-01-09 10:41:24.515 [error] <0.822.0> CRASH REPORT Process <0.822.0> with 0 neighbours exited with reason: {infrastructure_died,{writer,send_failed,badarg}} in gen_server:handle_common_reply/8 line 726
2020-01-09 10:41:24.516 [error] <0.820.0> Supervisor {<0.820.0>,amqp_channel_sup} had child channel started with amqp_channel:start_link(network, <0.813.0>, 1, <0.821.0>, {<<"client 127.0.0.1:51453 -> 127.0.0.1:5672">>,1}) at <0.822.0> exit with reason {infrastructure_died,{writer,send_failed,badarg}} in context child_terminated
2020-01-09 10:41:24.517 [error] <0.820.0> Supervisor {<0.820.0>,amqp_channel_sup} had child channel started with amqp_channel:start_link(network, <0.813.0>, 1, <0.821.0>, {<<"client 127.0.0.1:51453 -> 127.0.0.1:5672">>,1}) at <0.822.0> exit with reason reached_max_restart_intensity in context shutdown
2020-01-09 10:41:25.513 [error] emulator Error in process <0.826.0> with exit value:
{badarith,[{'Elixir.Tackle.ConnectionErrorsTest.DelayFailConsumer',handle_message,1,[{file,"test/integration/connection_errors_test.exs"},{line,52}]},{'Elixir.Tackle.ConnectionErrorsTest.DelayFailConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/connection_errors_test.exs"},{line,32}]}]}
2020-01-09 10:41:26.526 [error] <0.518.0> Supervisor 'Elixir.Tackle.Supervisor' had child 'Elixir.Tackle.Connection' started with 'Elixir.Tackle.Connection':start_link() at <0.519.0> exit with reason killed in context child_terminated
2020-01-09 10:41:26.690 [error] <0.870.0> gen_server <0.870.0> terminated with reason: {infrastructure_died,{writer,send_failed,badarg}}
2020-01-09 10:41:26.690 [error] <0.870.0> CRASH REPORT Process <0.870.0> with 0 neighbours exited with reason: {infrastructure_died,{writer,send_failed,badarg}} in gen_server:handle_common_reply/8 line 726
2020-01-09 10:41:26.691 [error] <0.859.0> Supervisor {<0.859.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.860.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,60000,none,[#Fun<amqp_..>,...],...}) at <0.861.0> exit with reason killed in context child_terminated
2020-01-09 10:41:26.691 [error] <0.868.0> Supervisor {<0.868.0>,amqp_channel_sup} had child channel started with amqp_channel:start_link(network, <0.861.0>, 1, <0.869.0>, {<<"client 127.0.0.1:42959 -> 127.0.0.1:5672">>,1}) at <0.870.0> exit with reason {infrastructure_died,{writer,send_failed,badarg}} in context child_terminated
2020-01-09 10:41:26.692 [error] <0.859.0> Supervisor {<0.859.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.860.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,60000,none,[#Fun<amqp_..>,...],...}) at <0.861.0> exit with reason reached_max_restart_intensity in context shutdown
2020-01-09 10:41:26.693 [error] <0.868.0> Supervisor {<0.868.0>,amqp_channel_sup} had child channel started with amqp_channel:start_link(network, <0.861.0>, 1, <0.869.0>, {<<"client 127.0.0.1:42959 -> 127.0.0.1:5672">>,1}) at <0.870.0> exit with reason reached_max_restart_intensity in context shutdown
2020-01-09 10:41:27.847 [error] emulator Error in process <0.1056.0> with exit value:
{badarith,[{'Elixir.Tackle.RepublishTest.BrokenConsumer',handle_message,1,[{file,"test/integration/republish_test.exs"},{line,17}]},{'Elixir.Tackle.RepublishTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/republish_test.exs"},{line,8}]}]}
2020-01-09 10:41:28.060 [error] emulator Error in process <0.1084.0> with exit value:
{badarith,[{'Elixir.Tackle.RepublishTest.BrokenConsumer',handle_message,1,[{file,"test/integration/republish_test.exs"},{line,17}]},{'Elixir.Tackle.RepublishTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/republish_test.exs"},{line,8}]}]}
2020-01-09 10:41:28.281 [error] emulator Error in process <0.1112.0> with exit value:
{badarith,[{'Elixir.Tackle.RepublishTest.BrokenConsumer',handle_message,1,[{file,"test/integration/republish_test.exs"},{line,17}]},{'Elixir.Tackle.RepublishTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/republish_test.exs"},{line,8}]}]}
2020-01-09 10:41:28.865 [error] emulator Error in process <0.1127.0> with exit value:
{badarith,[{'Elixir.Tackle.RepublishTest.BrokenConsumer',handle_message,1,[{file,"test/integration/republish_test.exs"},{line,17}]},{'Elixir.Tackle.RepublishTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/republish_test.exs"},{line,8}]}]}
2020-01-09 10:41:29.073 [error] emulator Error in process <0.1142.0> with exit value:
{badarith,[{'Elixir.Tackle.RepublishTest.BrokenConsumer',handle_message,1,[{file,"test/integration/republish_test.exs"},{line,17}]},{'Elixir.Tackle.RepublishTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/republish_test.exs"},{line,8}]}]}
2020-01-09 10:41:29.297 [error] emulator Error in process <0.1157.0> with exit value:
{badarith,[{'Elixir.Tackle.RepublishTest.BrokenConsumer',handle_message,1,[{file,"test/integration/republish_test.exs"},{line,17}]},{'Elixir.Tackle.RepublishTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/republish_test.exs"},{line,8}]}]}
2020-01-09 10:41:38.454 [error] emulator Error in process <0.1314.0> with exit value:
{badarith,[{'Elixir.Tackle.RepublishTest.BrokenConsumer',handle_message,1,[{file,"test/integration/republish_test.exs"},{line,17}]},{'Elixir.Tackle.RepublishTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/republish_test.exs"},{line,8}]}]}
2020-01-09 10:41:38.676 [error] emulator Error in process <0.1342.0> with exit value:
{badarith,[{'Elixir.Tackle.RepublishTest.BrokenConsumer',handle_message,1,[{file,"test/integration/republish_test.exs"},{line,17}]},{'Elixir.Tackle.RepublishTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/republish_test.exs"},{line,8}]}]}
2020-01-09 10:41:38.885 [error] emulator Error in process <0.1370.0> with exit value:
{badarith,[{'Elixir.Tackle.RepublishTest.BrokenConsumer',handle_message,1,[{file,"test/integration/republish_test.exs"},{line,17}]},{'Elixir.Tackle.RepublishTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/republish_test.exs"},{line,8}]}]}
2020-01-09 10:41:39.468 [error] emulator Error in process <0.1385.0> with exit value:
{badarith,[{'Elixir.Tackle.RepublishTest.BrokenConsumer',handle_message,1,[{file,"test/integration/republish_test.exs"},{line,17}]},{'Elixir.Tackle.RepublishTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/republish_test.exs"},{line,8}]}]}
2020-01-09 10:41:39.691 [error] emulator Error in process <0.1400.0> with exit value:
{badarith,[{'Elixir.Tackle.RepublishTest.BrokenConsumer',handle_message,1,[{file,"test/integration/republish_test.exs"},{line,17}]},{'Elixir.Tackle.RepublishTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/republish_test.exs"},{line,8}]}]}
2020-01-09 10:41:39.899 [error] emulator Error in process <0.1415.0> with exit value:
{badarith,[{'Elixir.Tackle.RepublishTest.BrokenConsumer',handle_message,1,[{file,"test/integration/republish_test.exs"},{line,17}]},{'Elixir.Tackle.RepublishTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/republish_test.exs"},{line,8}]}]}
2020-01-09 10:41:58.081 [error] emulator Error in process <0.1672.0> with exit value:
{badarith,[{'Elixir.Tackle.BrokenConsumerTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_test.exs"},{line,8}]}]}
2020-01-09 10:41:59.098 [error] emulator Error in process <0.1688.0> with exit value:
{badarith,[{'Elixir.Tackle.BrokenConsumerTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_test.exs"},{line,8}]}]}
2020-01-09 10:42:00.149 [error] emulator Error in process <0.1704.0> with exit value:
{badarith,[{'Elixir.Tackle.BrokenConsumerTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_test.exs"},{line,8}]}]}
2020-01-09 10:42:01.167 [error] emulator Error in process <0.1720.0> with exit value:
{badarith,[{'Elixir.Tackle.BrokenConsumerTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_test.exs"},{line,8}]}]}
2020-01-09 10:42:04.137 [error] emulator Error in process <0.1780.0> with exit value:
{{nocatch,{1,3,4}},[{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,8}]}]}
2020-01-09 10:42:05.191 [error] emulator Error in process <0.1796.0> with exit value:
{{nocatch,{1,3,4}},[{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,8}]}]}
2020-01-09 10:42:06.206 [error] emulator Error in process <0.1812.0> with exit value:
{{nocatch,{1,3,4}},[{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,8}]}]}
2020-01-09 10:42:07.261 [error] emulator Error in process <0.1828.0> with exit value:
{{nocatch,{1,3,4}},[{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerThrowsTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_throws_test.exs"},{line,8}]}]}
2020-01-09 10:42:09.218 [error] emulator Error in process <0.1914.0> with exit value:
{badarith,[{'Elixir.Tackle.DeadQueueTest.DeadConsumer',handle_message,1,[{file,"test/integration/dead_queue_test.exs"},{line,16}]},{'Elixir.Tackle.DeadQueueTest.DeadConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/dead_queue_test.exs"},{line,7}]}]}
2020-01-09 10:42:10.237 [error] emulator Error in process <0.1929.0> with exit value:
{badarith,[{'Elixir.Tackle.DeadQueueTest.DeadConsumer',handle_message,1,[{file,"test/integration/dead_queue_test.exs"},{line,16}]},{'Elixir.Tackle.DeadQueueTest.DeadConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/dead_queue_test.exs"},{line,7}]}]}
2020-01-09 10:42:11.291 [error] emulator Error in process <0.1944.0> with exit value:
{badarith,[{'Elixir.Tackle.DeadQueueTest.DeadConsumer',handle_message,1,[{file,"test/integration/dead_queue_test.exs"},{line,16}]},{'Elixir.Tackle.DeadQueueTest.DeadConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/dead_queue_test.exs"},{line,7}]}]}
2020-01-09 10:42:12.308 [error] emulator Error in process <0.1959.0> with exit value:
{badarith,[{'Elixir.Tackle.DeadQueueTest.DeadConsumer',handle_message,1,[{file,"test/integration/dead_queue_test.exs"},{line,16}]},{'Elixir.Tackle.DeadQueueTest.DeadConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/dead_queue_test.exs"},{line,7}]}]}
2020-01-09 10:42:15.289 [error] emulator Error in process <0.2031.0> with exit value:
{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Raised!">>},[{'Elixir.Tackle.BrokenConsumerRaisesTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_raises_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerRaisesTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_raises_test.exs"},{line,8}]}]}
2020-01-09 10:42:16.344 [error] emulator Error in process <0.2047.0> with exit value:
{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Raised!">>},[{'Elixir.Tackle.BrokenConsumerRaisesTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_raises_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerRaisesTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_raises_test.exs"},{line,8}]}]}
2020-01-09 10:42:17.360 [error] emulator Error in process <0.2063.0> with exit value:
{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Raised!">>},[{'Elixir.Tackle.BrokenConsumerRaisesTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_raises_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerRaisesTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_raises_test.exs"},{line,8}]}]}
2020-01-09 10:42:18.414 [error] emulator Error in process <0.2079.0> with exit value:
{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Raised!">>},[{'Elixir.Tackle.BrokenConsumerRaisesTest.BrokenConsumer',handle_message,1,[{file,"test/integration/broken_consumer_raises_test.exs"},{line,19}]},{'Elixir.Tackle.BrokenConsumerRaisesTest.BrokenConsumer','-handle_info/2-fun-0-',3,[{file,"test/integration/broken_consumer_raises_test.exs"},{line,8}]}]}
2020-01-09 10:42:28.381 [error] <0.518.0> Supervisor 'Elixir.Tackle.Supervisor' had child 'Elixir.Tackle.Connection' started with 'Elixir.Tackle.Connection':start_link() at <0.856.0> exit with reason killed in context child_terminated
2020-01-09 10:42:28.491 [error] <0.2240.0> Supervisor {<0.2240.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2241.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,60000,none,[#Fun<amqp_..>,...],...}) at <0.2242.0> exit with reason killed in context child_terminated
2020-01-09 10:42:28.492 [error] <0.2240.0> Supervisor {<0.2240.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2241.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,60000,none,[#Fun<amqp_..>,...],...}) at <0.2242.0> exit with reason reached_max_restart_intensity in context shutdown
